# Generated by Django 6.0.4 on 2026-04-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0003_data_menus_opciones_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['rol', 'opcion']},
        ),
        migrations.AlterField(
            model_name='permiso',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('director_grupo', 'Director de Grupo'), ('director_semillero', 'Director de Semillero'), ('lider_estudiantil', 'Líder Estudiantil'), ('estudiante', 'Estudiante')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('director_grupo', 'Director de Grupo'), ('director_semillero', 'Director de Semillero'), ('lider_estudiantil', 'Líder Estudiantil'), ('estudiante', 'Estudiante')], default='estudiante', max_length=30, verbose_name='Rol'),
        ),
    ]
