# Generated by Django 6.0.4 on 2026-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0004_alter_menu_options_alter_opcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Personal'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_graduated',
            field=models.BooleanField(default=False, verbose_name='Es egresado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email institucional'),
        ),
    ]
