# Generated by Django 6.0.4 on 2026-04-20 21:45

from django.db import migrations

def copy_email_to_correo_personal(apps, schema_editor):
    User = apps.get_model('sigesi', 'User')
    for user in User.objects.all():
        if user.email:
            user.correo_personal = user.email
            user.save(update_fields=['correo_personal'])

def reverse_copy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0005_user_correo_personal_user_is_graduated_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_email_to_correo_personal, reverse_copy),
    ]
