# Generated by Django 6.0.4 on 2026-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0006_auto_20260420_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='correo_personal',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Personal'),
        ),
    ]
