# Generated by Django 6.0.4 on 2026-04-28 21:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0007_alter_user_correo_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('administrador', 'Administrador'), ('director_grupo', 'Director de Grupo'), ('director_semillero', 'Director de Semillero'), ('lider_estudiantil', 'Líder Estudiantil'), ('estudiante', 'Estudiante')], max_length=30), default=list, help_text='Lista de roles asignados al usuario.', verbose_name='Roles'),
        ),
    ]
