# Generated by Django 6.0.4 on 2026-04-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0009_migrate_rol_to_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
    ]
