# Generated by Django 6.0.4 on 2026-05-15 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0010_user_remove_old_rol_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=300, verbose_name='Actividad')),
                ('descripcion_actividad', models.TextField(verbose_name='Descripción de la actividad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('estado_actividad', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada')], default='pendiente', max_length=20, verbose_name='Estado de la actividad')),
                ('archivo_cronograma', models.FileField(blank=True, null=True, upload_to='cronogramas_proyecto/%Y/%m/', verbose_name='Archivo del cronograma')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='sigesi.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Cronograma de Proyecto',
                'verbose_name_plural': 'Cronogramas de Proyecto',
                'ordering': ['proyecto', 'fecha_inicio'],
            },
        ),
    ]
