# Generated by Django 6.0.4 on 2026-05-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0010_user_remove_old_rol_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha del avance')),
                ('porcentaje', models.PositiveIntegerField(default=0, help_text='Valor entre 0 y 100.', verbose_name='Porcentaje de avance')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del revisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='sigesi.proyecto', verbose_name='Proyecto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='avances/%Y/%m/', verbose_name='Archivo de evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='sigesi.avance', verbose_name='Avance')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_avance_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Evidencia de Avance',
                'verbose_name_plural': 'Evidencias de Avance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='avance',
            index=models.Index(fields=['proyecto', 'estado'], name='sigesi_avan_proyect_5af9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='avance',
            index=models.Index(fields=['registrado_por'], name='sigesi_avan_registr_3c9d1c_idx'),
        ),
    ]
