# Generated by Django 6.0.4 on 2026-05-15 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0011_cronogramaproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación')),
                ('estado_proyecto', models.CharField(choices=[('idea', 'Idea'), ('propuesta', 'Propuesta'), ('en_ejecucion', 'En Ejecución'), ('en_resultados', 'En Resultados'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado del proyecto')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_proyecto_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_proyecto', to='sigesi.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Evaluación de Proyecto',
                'verbose_name_plural': 'Evaluaciones de Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
