# Generated by Django 6.0.4 on 2026-05-11 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0011_add_avance_evidenciaavance'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='avance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='sigesi.avance', verbose_name='Avance'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='sigesi.actividad', verbose_name='Actividad'),
        ),
        migrations.DeleteModel(
            name='EvidenciaAvance',
        ),
    ]
