# Generated by Django 6.0.4 on 2026-05-15 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0012_evaluacionproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='archivo_aval',
            field=models.FileField(blank=True, null=True, upload_to='semilleros/avales/%Y/%m/', verbose_name='Archivo del aval'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='estado_aval',
            field=models.CharField(choices=[('sin_aprobar', 'Sin Aprobar'), ('en_proceso', 'En Proceso'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='sin_aprobar', max_length=20, verbose_name='Estado del aval'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='numero_acta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de acta'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones del aval'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('acta', 'Acta'), ('resolucion', 'Resolución'), ('oficio', 'Oficio'), ('certificado', 'Certificado')], max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semilleros_avalados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que aprobó'),
        ),
    ]
