# Generated by Django 6.0.4 on 2026-05-11 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0012_use_evidencia_for_avances'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_proyecto', models.CharField(choices=[('investigador', 'Investigador Principal'), ('coinvestigador', 'Co-investigador'), ('auxiliar', 'Auxiliar de Investigación'), ('otro', 'Otro')], default='auxiliar', max_length=20, verbose_name='Rol en el proyecto')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('estado_participacion', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado de participación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_proyecto', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='sigesi.proyecto')),
            ],
            options={
                'verbose_name': 'Participante de Proyecto',
                'verbose_name_plural': 'Participantes de Proyecto',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('proyecto', 'estudiante')},
            },
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='proyectos_vinculados', through='sigesi.ProyectoEstudiante', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes vinculados'),
        ),
    ]
