# Generated by Django 6.0.4 on 2026-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0013_semillero_archivo_aval_semillero_estado_aval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='mision',
            field=models.TextField(blank=True, verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='lineainvestigacion',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Visión'),
        ),
    ]
