# Generated by Django 6.0.4 on 2026-05-22 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0015_lider_implica_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='actividad',
        ),
        migrations.CreateModel(
            name='ActividadCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('objetivo_general', models.TextField(blank=True, verbose_name='Objetivo general')),
                ('objetivos_especificos', models.TextField(blank=True, verbose_name='Objetivos específicos')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha de fin estimada')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='sigesi.cronograma', verbose_name='Cronograma')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_cronograma', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Actividad de Cronograma',
                'verbose_name_plural': 'Actividades de Cronograma',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
