# Generated by Django 6.0.4 on 2026-05-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0017_planestrategico_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planestrategico',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_ejecucion', 'En Ejecución'), ('finalizado', 'Finalizado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
