# Generated by Django 6.0.4 on 2026-05-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0018_alter_planestrategico_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaccion',
            name='objetivos',
        ),
        migrations.CreateModel(
            name='ObjetivosPlanAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('academicos', 'Académicos'), ('investigativos', 'Investigativos'), ('administrativos', 'Administrativos'), ('institucionales', 'Institucionales')], max_length=20, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='sigesi.planaccion', verbose_name='Plan de acción')),
            ],
            options={
                'verbose_name': 'Objetivo de Plan de Acción',
                'verbose_name_plural': 'Objetivos de Plan de Acción',
                'ordering': ['id'],
            },
        ),
    ]
