# Generated by Django 6.0.4 on 2026-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0019_remove_planaccion_objetivos_objetivosplanaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcronograma',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
