# Generated by Django 6.0.4 on 2026-05-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0021_alter_evaluacion_nivel_alcanzado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_vinculacion',
            field=models.CharField(blank=True, choices=[('catedratico', 'Catedrático'), ('planta', 'Planta')], help_text='Tipo de vinculación del director de semillero (catedrático o planta). Determina el conjunto de formatos institucionales que puede descargar.', max_length=20, null=True, verbose_name='Tipo de vinculación'),
        ),
    ]
