# Generated by Django 6.0.4 on 2026-06-01 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sigesi', '0026_workflow_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('convocatoria_creada', 'Convocatoria creada'), ('convocatoria_actualizada', 'Convocatoria actualizada'), ('postulacion_creada', 'Postulación creada'), ('postulacion_actualizada', 'Postulación actualizada'), ('participacion_creada', 'Participación registrada'), ('participacion_actualizada', 'Participación actualizada')], max_length=40, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='sigesi_noti_usuario_08cac0_idx'), models.Index(fields=['usuario', 'leida'], name='sigesi_noti_usuario_a06fa4_idx')],
                'unique_together': {('usuario', 'tipo', 'content_type', 'object_id')},
            },
        ),
    ]
