# Generated by Django 6.0.4 on 2026-06-02 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0027_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.CharField(blank=True, help_text='Copia del correo institucional (o personal) al momento del evento.', max_length=254, verbose_name='Correo del usuario')),
                ('rol_activo', models.CharField(blank=True, help_text='Rol seleccionado en el token (claim role) al ejecutar la acción.', max_length=30, verbose_name='Rol activo')),
                ('accion', models.CharField(choices=[('acceso', 'Acceso al sistema'), ('autenticacion', 'Autenticación'), ('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('eliminacion', 'Eliminación'), ('consulta', 'Consulta')], max_length=20, verbose_name='Acción')),
                ('modulo', models.CharField(help_text='Recurso afectado, inferido de la URL (p. ej. actividades).', max_length=80, verbose_name='Módulo')),
                ('metodo_http', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('ruta', models.CharField(max_length=255, verbose_name='Ruta')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Código de estado')),
                ('object_id', models.CharField(blank=True, help_text='PK del recurso afectado cuando puede inferirse de la URL.', max_length=64, verbose_name='ID del objeto')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Agente de usuario')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['accion'], name='sigesi_regi_accion_a9b512_idx'), models.Index(fields=['modulo'], name='sigesi_regi_modulo_89e9cc_idx'), models.Index(fields=['usuario'], name='sigesi_regi_usuario_f2bfa5_idx')],
            },
        ),
    ]
