# Generated by Django 6.0.4 on 2026-09-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0028_registroauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='tipo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('especial', 'Especial')], max_length=20, verbose_name='Tipo'),
        ),
    ]
