# Generated by Django 6.0.4 on 2026-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigesi', '0030_seed_rbac_documental'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('planeacion', 'Planeación'), ('gestion', 'Gestión'), ('administrativos_y_academicos', 'Administrativos y Académicos'), ('mensual', 'Mensual')], max_length=40, verbose_name='Categoría')),
                ('archivo', models.FileField(upload_to='formatos/%Y/', verbose_name='Archivo')),
                ('tipo_vinculacion', models.CharField(blank=True, choices=[('catedratico', 'Catedrático'), ('planta', 'Planta')], help_text='Vacío = aplica a todos los tipos de vinculación.', max_length=20, null=True, verbose_name='Tipo de vinculación')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Versión')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formato Institucional',
                'verbose_name_plural': 'Formatos Institucionales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
